Added 3 new pages, AWG, EWG and how to join them
openhwgroup/openhwgroup.org pull request #436
Opened 2022-04-07 18:49 UTC by linkfang

Signed-off-by: Zhou Fang <zhou.fang@eclipse-foundation.org>

Fixes https://github.com/openhwgroup/openhwgroup.org/issues/434

2022-04-29 18:54 UTC, linkfang commented
Got +1 from Duncan, https://github.com/openhwgroup/openhwgroup.org/issues/434#issuecomment-1113626289

2022-04-29 18:59 UTC, autumnfound requested changes
Do not merge. See bottom of working-groups page, it is including list entries for the other pages which is not what we want. You'll want to change the layout of the working groups page to account for this (I believe we want single here)

2022-05-04 18:27 UTC, linkfang commented
Got +1 from Duncan for updated content, https://github.com/openhwgroup/openhwgroup.org/issues/434#issuecomment-1117666909

2022-05-04 20:01 UTC, autumnfound approved these changes

2022-05-04 20:20 UTC, merged